# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sendex < Formula
  desc "A lightweight API endpoint testing tool."
  homepage ""
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hadlow/sendex/releases/download/v1.1.2/sendex_Darwin_x86_64.tar.gz"
      sha256 "048cc214bb5e72f1d362c0402af120138a4ec8a9d8a3c68b8783ddd5f0339d70"

      def install
        bin.install "sendex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hadlow/sendex/releases/download/v1.1.2/sendex_Darwin_arm64.tar.gz"
      sha256 "0089c01cfa60fc9294c73d5e6f334cc50044f02dd3f4631a8094808e3f889d2d"

      def install
        bin.install "sendex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/sendex/releases/download/v1.1.2/sendex_Linux_x86_64.tar.gz"
        sha256 "c30360c143ca1421687eb34f67a22e73371098e1dde9dfbf7e59a156ca4c6078"

        def install
          bin.install "sendex"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/sendex/releases/download/v1.1.2/sendex_Linux_arm64.tar.gz"
        sha256 "9916dc446ba0c08839c7c5d7686a7941b08c79c5bd8e2e72ffc778d661d73324"

        def install
          bin.install "sendex"
        end
      end
    end
  end

  test do
    system "#{bin}/sendex --version"
  end
end
