# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sendex < Formula
  desc "A lightweight API endpoint testing tool."
  homepage ""
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hadlow/sendex/releases/download/v1.1.1/sendex_Darwin_x86_64.tar.gz"
      sha256 "52129110461d122d58b3a72b4903d44fd671c70dafa3effbdaccce19c0b50264"

      def install
        bin.install "sendex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hadlow/sendex/releases/download/v1.1.1/sendex_Darwin_arm64.tar.gz"
      sha256 "c6df24c354a626663221745ddbd2deb727611ef8ad110fc48ea6cb76175f4f6b"

      def install
        bin.install "sendex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/sendex/releases/download/v1.1.1/sendex_Linux_x86_64.tar.gz"
        sha256 "bcb469ea11c317a2aa2b79b1ac9337e7d89a19e26f2bc52644ca9586c5a92db9"

        def install
          bin.install "sendex"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/sendex/releases/download/v1.1.1/sendex_Linux_arm64.tar.gz"
        sha256 "a0e2d7c7e96236443beee547cf7c469bf9c5b663373d3f87f4ac6abcded132b2"

        def install
          bin.install "sendex"
        end
      end
    end
  end

  test do
    system "#{bin}/sendex --version"
  end
end
