# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sendex < Formula
  desc "A lightweight API endpoint testing tool."
  homepage ""
  version "1.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hadlow/sendex/releases/download/v1.2.3/sendex_Darwin_x86_64.tar.gz"
      sha256 "384c1df638ce4f97efd57ecf5946d751304aa7bf8c45bb8a2df06d241a1cfc15"

      def install
        bin.install "sendex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hadlow/sendex/releases/download/v1.2.3/sendex_Darwin_arm64.tar.gz"
      sha256 "6350e20465355cd3dcbfb49fee0738b92dde40752fd10e5a48a80a7e4a3fd0a5"

      def install
        bin.install "sendex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/sendex/releases/download/v1.2.3/sendex_Linux_x86_64.tar.gz"
        sha256 "e9ef57323b4b0f2e530472aef793f1cef59459c2f33aec77e4a8f04f0373deae"

        def install
          bin.install "sendex"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hadlow/sendex/releases/download/v1.2.3/sendex_Linux_arm64.tar.gz"
        sha256 "dbc8308b80e69f2ed4d628b9bdaf6f0d981f1e9479df8f735402d7d53c9cac6c"

        def install
          bin.install "sendex"
        end
      end
    end
  end

  test do
    system "#{bin}/sendex --version"
  end
end
